"""
Self-Consistency Check for Hallucination Detection.

Detects potential hallucinations by measuring semantic consistency
between the original LLM answer and multiple verification answers.
"""

import numpy as np
from sentence_transformers import SentenceTransformer, util
from typing import List, Tuple


class SelfConsistencyCheck:
    """
    Hallucination Detection via Self-Consistency.

    Generates multiple verification answers and compares semantic similarity
    to detect potential hallucinations.
    """

    def __init__(
        self,
        llm,
        num_verifications: int = 3,
        block_threshold: float = 0.5,
        warn_threshold: float = 0.75,
    ):
        """
        Initialize the Self-Consistency Check.

        Args:
            llm: The LLM instance to use for generating verification answers
            num_verifications: Number of verification answers to generate
            block_threshold: avg_sim below this = BLOCK
            warn_threshold: avg_sim below this = WARN
        """
        self.llm = llm
        self.num_verifications = num_verifications
        self.block_threshold = block_threshold
        self.warn_threshold = warn_threshold

        # Load SentenceTransformer model for semantic similarity
        print("[DEBUG][Self-Consistency] Loading SentenceTransformer model...")
        self.encoder = SentenceTransformer("all-MiniLM-L6-v2")
        print("[DEBUG][Self-Consistency] Model loaded successfully")

    def _generate_verification(self, original_answer: str, question: str, temperature: float) -> str:
        """
        Generate a verification answer using fact-checker style prompt.

        Args:
            original_answer: The original LLM answer to verify
            question: The original user question
            temperature: Temperature for generation

        Returns:
            Verification answer string
        """
        fact_check_prompt = f"""You are a meticulous fact-checker.

Original Question: {question}

Original Answer: {original_answer}

Your task: Evaluate the above answer for factual accuracy.
If it is accurate, provide a similar response to the original question.
If it is inaccurate, provide the correct answer.

Your response:"""

        # Use the LLM with specified temperature
        from langchain_openai import ChatOpenAI
        import config

        verification_llm = ChatOpenAI(
            model=config.OPENAI_MODEL,
            api_key=config.OPENAI_API_KEY,
            temperature=temperature
        )

        response = verification_llm.invoke(fact_check_prompt)
        return response.content

    def check(self, original_answer: str, question: str) -> Tuple[str, float, str]:
        """
        Perform self-consistency check on the original answer.

        Args:
            original_answer: The initial response generated by the LLM
            question: The original user query

        Returns:
            Tuple of (verdict, avg_similarity, action)
            - verdict: "BLOCK", "WARN", or "ALLOW"
            - avg_similarity: Average cosine similarity score
            - action: Same as verdict
        """
        print(f"\n[DEBUG][Self-Consistency] Starting check...")
        print(f"[DEBUG][Self-Consistency] Original answer length: {len(original_answer)}")

        # Generate verification answers with different temperatures
        temperatures = [0.3, 0.7, 1.0]
        verification_answers: List[str] = []

        for i, temp in enumerate(temperatures[:self.num_verifications]):
            print(f"[DEBUG][Self-Consistency] Generating verification {i+1} with temperature={temp}")
            try:
                verification = self._generate_verification(original_answer, question, temp)
                verification_answers.append(verification)
                print(f"[DEBUG][Self-Consistency] Verification {i+1} generated (length: {len(verification)})")
            except Exception as e:
                print(f"[DEBUG][Self-Consistency] Error generating verification {i+1}: {e}")

        if not verification_answers:
            print("[DEBUG][Self-Consistency] No verification answers generated, defaulting to ALLOW")
            print("[DEBUG][Self-Consistency] avg_sim = N/A")
            print("[DEBUG][Self-Consistency] verdict = ALLOW")
            print("[DEBUG][Self-Consistency] verification_count = 0")
            return ("ALLOW", 1.0, "ALLOW")

        # Encode all texts
        all_texts = [original_answer] + verification_answers
        embeddings = self.encoder.encode(all_texts, convert_to_tensor=True)

        # Compute cosine similarities between original and each verification
        similarities = util.cos_sim(embeddings[0], embeddings[1:]).flatten()
        avg_sim = float(np.mean([s.item() for s in similarities]))

        # Determine verdict based on thresholds
        if avg_sim < self.block_threshold:
            verdict = "BLOCK"
        elif avg_sim < self.warn_threshold:
            verdict = "WARN"
        else:
            verdict = "ALLOW"

        # Print debug logs (MANDATORY)
        print(f"[DEBUG][Self-Consistency] avg_sim = {avg_sim:.4f}")
        print(f"[DEBUG][Self-Consistency] verdict = {verdict}")
        print(f"[DEBUG][Self-Consistency] verification_count = {len(verification_answers)}")

        return (verdict, avg_sim, verdict)
